### ISSUE TITLE
Can't right click on airwaysmag.com

### ISSUE THREAD

**Issue by CaviaPorcellus** [lunu-bounir/allow-right-click#27]
Right-clicking is blocked on airwaysmag.com despite Allow Right-Click being active.

To reproduce:
Navigate to https://airwaysmag.com/
Try to right click on the homepage or any article.

Thanks for the add-on.

Allow Right-Click version 0.5.0
Firefox 100.0.2
Kubuntu 22.04

**Comment by lunu-bounir** [comment]
I tried on Ubuntu and it works for me. Can you try on a clean profile?

**Comment by Gabri04** [comment]
> Right-clicking is blocked on airwaysmag.com despite Allow Right-Click being active.
> 
> To reproduce: Navigate to https://airwaysmag.com/ Try to right click on the homepage or any article.
> 
> Thanks for the add-on.
> 
> Allow Right-Click version 0.5.0 Firefox 100.0.2 Kubuntu 22.04

Tried with Edge just for fun, it doesn't work
