### ISSUE TITLE
Please Add Copy Paste to Context Menu on Right Click

### ISSUE THREAD

**Issue by linuxstv** [lunu-bounir/allow-right-click#36]
This is when I right click on an input box of a website:

![Screenshot_20240211_190043](https://github.com/lunu-bounir/allow-right-click/assets/15664372/655d7ffa-ff78-4a41-8d2f-8cea4e41d017)

The missing context are: Cut, Copy, Paste.

Result should be as this one (using other extension):

![Screenshot_20240211_191804](https://github.com/lunu-bounir/allow-right-click/assets/15664372/6a623182-a3a3-455d-8b3a-b87d853648a7)

I hope you can add it to the extension.
Thank you.

**Comment by lunu-bounir** [comment]
Can you share a sample page? Does the Ctrl + C work?

**Comment by linuxstv** [comment]
> Can you share a sample page? Does the Ctrl + C work?

CTRL+C doesn't work too. Here's a sample page:
https://cms.bankkalbar.co.id
