### ISSUE TITLE
Why is the extension published by WebExtension.ORG?

### ISSUE THREAD

**Issue by github-account1111** [lunu-bounir/allow-right-click#40]
Looks like a shady site that publishes [hundreds of random extensions].

I've found other similar ["extension farms"] publishing hundreds of other random extensions.

Is this the norm now? Since when? Why not publish yourself? Would look much less shady, and it's not like Microsoft or Google charge you to publish extensions (unlike Apple). I was about to not install this because I thought this'll have a hidden crypto miner lol.

[hundreds of random extensions]: https://webextension.org/
["extension farms"]: https://mybrowseraddon.com/

**Comment by lunu-bounir** [comment]
By listing in this free hosting, I got more attraction on my extension. The source code is also open.

I don't think you can find anything shady on this hosting. There are manual reviews for all submissions.

**Comment by github-account1111** [comment]
> I don't think you can find anything shady on this hosting. There are manual reviews for all submissions.

I certainly believe you, but my point was it *looked* shady at a first glance. I actually couldn't even find a link to this repo for quite a while. It's nowhere to be found on the page linked from the extension store.

I thought those WebExtension guys just churn out hundreds of low-quality data-mining extensions using ChatGPT. I was obviously wrong, but that was my first impression.
