### ISSUE TITLE
Add support for enabling long-press on Android 

### ISSUE THREAD

**Issue by pkoepke** [lunu-bounir/allow-right-click#41]
Many sites that suppress right-click also suppress the long-press menu on Android, possibly through the same mechanism. It would be nice if this extension could enable right-click and long press.

**Comment by lunu-bounir** [comment]
Since we already support `touchstart`, the long press should bring up the default menu. If there is an example page that the extension does not work, please provide a sample.

**Comment by lunu-bounir** [comment]
I see. The next release is marked as compatible.

**Comment by pkoepke** [comment]
Thanks!
